apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-Deployment
  labels:
    app: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: 818341956246.dkr.ecr.us-east-2.amazonaws.com/test:e0432b77e83cbfb6dbd5eb79ebcd84bbdf469865
        ports:
        - containerPort: 8080